### ISSUE TITLE
Problems about the data and path

### ISSUE THREAD

**Issue by Lpn-98** [sunlab-osu/TURL#13]
Hi, I am a university student who is new to NLP field, and my supervisor recommended me to study this TURL paper and the code.
I download all the files and data and try to run the "train.py", but it cannot run because of many uncomplete or wrong path. I searched and tried many actions but failed.
I am wondering whether anybody can run the code of this paper, and may I have any advice about how to run it smoothly?

Thanks very much and hope everything goes well.

**Comment by xiang-deng** [comment]
Hi, could you let me know about the specific files that are missing? Due to the constraint on file size, we share the data in Box, you should download them to local storage and change the paths accordingly. Note that there are multiple pages in the Box share, make sure you check and downloaded all of them. Thanks.
