### ISSUE TITLE
which pytorch_model.bin should i use?

### ISSUE THREAD

**Issue by Typooner** [sunlab-osu/TURL#22]
The data path in the code does not correspond to the data in the given link. When I try to use pre_ train_ hybrid_ During the pre training of v2.sh, the following error occurred due to data file issues:
![image](https://user-images.githubusercontent.com/55538775/234159000-e29697f7-bfdd-4c8f-8229-86da0fadecf8.png)

I downloaded this file in onedrive's checkpoint/pretrained/pytorch_model.bin, but one new error occurred . Did I download the wrong model file?
![image](https://user-images.githubusercontent.com/55538775/234159122-c2ef76ba-26d5-4947-9502-881f6cc6440b.png)

**Comment by xiang-deng** [comment]
Hi, with `lm_finetuning` I think you want to further pretrain the model with self-supervised objectives? For the first error, as suggest by the error message, you can download [tiny-bert](https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/TinyBERT) here which is what I used to initialize the model. 
If you want to start with our pretrained checkpoint, I think the issue is the prefix `bert`. Huggingface model typically has the following the structure:
```
def model():
    self.bert = BertModel()
```
So when saving the model, the state dict will have a prefix `bert`, but the true model we need is just the `BertModel`, which is what we shared and does not have the prefix.

**Comment by Typooner** [comment]
Thank you for your prompt response. I chose the first method you mentioned and downloaded the model file. However, during the subsequent training process, I encountered this problem.
![98b40c97ea6ae846f3ac63027208470c](https://user-images.githubusercontent.com/55538775/234481679-416d50eb-1aa3-4bd2-ac20-5c30c6ad5bba.png)
I found this problem in hybrid_data_loaders.py
![image](https://user-images.githubusercontent.com/55538775/234481783-36eaf670-dbf9-4aac-99c8-85eb841f2d52.png)
Perhaps there were some issues with my data preprocessing, here is my data file,could you please give me some advice?
![image](https://user-images.githubusercontent.com/55538775/234482033-51f6535a-6ab8-45bc-bc60-4e9006d0be62.png)

**Comment by Typooner** [comment]
Thank you for your suggestion. I adopted the first method and successfully ran the model~
